/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NewRouteImport } from './routes/new'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as EntriesSlugRouteImport } from './routes/entries/$slug'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TopicsIdRouteImport } from './routes/topics/$id'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiV1DumpRouteImport } from './routes/api/v1/dump'
import { Route as ApiV1GraphRouteImport } from './routes/api/v1/graph'
import { Route as ApiV1SchemaRouteImport } from './routes/api/v1/schema'
import { Route as ApiV1SearchRouteImport } from './routes/api/v1/search'
import { Route as ApiV1EntriesIndexRouteImport } from './routes/api/v1/entries/index'
import { Route as ApiV1EntriesIdRouteImport } from './routes/api/v1/entries/$id'
import { Route as ApiV1RefsIndexRouteImport } from './routes/api/v1/refs/index'
import { Route as ApiV1RefsKeyRouteImport } from './routes/api/v1/refs/$key'
import { Route as ApiV1TopicsIndexRouteImport } from './routes/api/v1/topics/index'
import { Route as ApiV1TopicsIdRouteImport } from './routes/api/v1/topics/$id'
import { Route as ApiV1TopicsIdEntriesIndexRouteImport } from './routes/api/v1/topics/$id/entries/index'
import { Route as ApiV1TopicsIdEntriesSlugRouteImport } from './routes/api/v1/topics/$id/entries/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesSlugRoute = EntriesSlugRouteImport.update({
  id: '/entries/$slug',
  path: '/entries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIdRoute = TopicsIdRouteImport.update({
  id: '/topics/$id',
  path: '/topics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DumpRoute = ApiV1DumpRouteImport.update({
  id: '/api/v1/dump',
  path: '/api/v1/dump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GraphRoute = ApiV1GraphRouteImport.update({
  id: '/api/v1/graph',
  path: '/api/v1/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SchemaRoute = ApiV1SchemaRouteImport.update({
  id: '/api/v1/schema',
  path: '/api/v1/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/api/v1/search',
  path: '/api/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntriesIndexRoute = ApiV1EntriesIndexRouteImport.update({
  id: '/api/v1/entries/',
  path: '/api/v1/entries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntriesIdRoute = ApiV1EntriesIdRouteImport.update({
  id: '/api/v1/entries/$id',
  path: '/api/v1/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RefsIndexRoute = ApiV1RefsIndexRouteImport.update({
  id: '/api/v1/refs/',
  path: '/api/v1/refs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RefsKeyRoute = ApiV1RefsKeyRouteImport.update({
  id: '/api/v1/refs/$key',
  path: '/api/v1/refs/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TopicsIndexRoute = ApiV1TopicsIndexRouteImport.update({
  id: '/api/v1/topics/',
  path: '/api/v1/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TopicsIdRoute = ApiV1TopicsIdRouteImport.update({
  id: '/api/v1/topics/$id',
  path: '/api/v1/topics/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TopicsIdEntriesIndexRoute =
  ApiV1TopicsIdEntriesIndexRouteImport.update({
    id: '/entries/',
    path: '/entries/',
    getParentRoute: () => ApiV1TopicsIdRoute,
  } as any)
const ApiV1TopicsIdEntriesSlugRoute =
  ApiV1TopicsIdEntriesSlugRouteImport.update({
    id: '/entries/$slug',
    path: '/entries/$slug',
    getParentRoute: () => ApiV1TopicsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/topics/$id': typeof TopicsIdRoute
  '/api/': typeof ApiIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/dump': typeof ApiV1DumpRoute
  '/api/v1/graph': typeof ApiV1GraphRoute
  '/api/v1/schema': typeof ApiV1SchemaRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/entries/$id': typeof ApiV1EntriesIdRoute
  '/api/v1/refs/$key': typeof ApiV1RefsKeyRoute
  '/api/v1/topics/$id': typeof ApiV1TopicsIdRouteWithChildren
  '/api/v1/entries/': typeof ApiV1EntriesIndexRoute
  '/api/v1/refs/': typeof ApiV1RefsIndexRoute
  '/api/v1/topics/': typeof ApiV1TopicsIndexRoute
  '/api/v1/topics/$id/entries/$slug': typeof ApiV1TopicsIdEntriesSlugRoute
  '/api/v1/topics/$id/entries/': typeof ApiV1TopicsIdEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/topics/$id': typeof TopicsIdRoute
  '/api': typeof ApiIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/dump': typeof ApiV1DumpRoute
  '/api/v1/graph': typeof ApiV1GraphRoute
  '/api/v1/schema': typeof ApiV1SchemaRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/api/v1/entries/$id': typeof ApiV1EntriesIdRoute
  '/api/v1/refs/$key': typeof ApiV1RefsKeyRoute
  '/api/v1/topics/$id': typeof ApiV1TopicsIdRouteWithChildren
  '/api/v1/entries': typeof ApiV1EntriesIndexRoute
  '/api/v1/refs': typeof ApiV1RefsIndexRoute
  '/api/v1/topics': typeof ApiV1TopicsIndexRoute
  '/api/v1/topics/$id/entries/$slug': typeof ApiV1TopicsIdEntriesSlugRoute
  '/api/v1/topics/$id/entries': typeof ApiV1TopicsIdEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/entries/$slug': typeof EntriesSlugRoute
  '/topics/$id': typeof TopicsIdRoute
  '/api/': typeof ApiIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/dump': typeof ApiV1DumpRoute
  '/api/v1/graph': typeof ApiV1GraphRoute
  '/api/v1/schema': typeof ApiV1SchemaRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/entries/$id': typeof ApiV1EntriesIdRoute
  '/api/v1/refs/$key': typeof ApiV1RefsKeyRoute
  '/api/v1/topics/$id': typeof ApiV1TopicsIdRouteWithChildren
  '/api/v1/entries/': typeof ApiV1EntriesIndexRoute
  '/api/v1/refs/': typeof ApiV1RefsIndexRoute
  '/api/v1/topics/': typeof ApiV1TopicsIndexRoute
  '/api/v1/topics/$id/entries/$slug': typeof ApiV1TopicsIdEntriesSlugRoute
  '/api/v1/topics/$id/entries/': typeof ApiV1TopicsIdEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/llms.txt'
    | '/new'
    | '/entries/$slug'
    | '/topics/$id'
    | '/api/'
    | '/topics/'
    | '/api/v1/$'
    | '/api/v1/dump'
    | '/api/v1/graph'
    | '/api/v1/schema'
    | '/api/v1/search'
    | '/api/v1/'
    | '/api/v1/entries/$id'
    | '/api/v1/refs/$key'
    | '/api/v1/topics/$id'
    | '/api/v1/entries/'
    | '/api/v1/refs/'
    | '/api/v1/topics/'
    | '/api/v1/topics/$id/entries/$slug'
    | '/api/v1/topics/$id/entries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/llms.txt'
    | '/new'
    | '/entries/$slug'
    | '/topics/$id'
    | '/api'
    | '/topics'
    | '/api/v1/$'
    | '/api/v1/dump'
    | '/api/v1/graph'
    | '/api/v1/schema'
    | '/api/v1/search'
    | '/api/v1'
    | '/api/v1/entries/$id'
    | '/api/v1/refs/$key'
    | '/api/v1/topics/$id'
    | '/api/v1/entries'
    | '/api/v1/refs'
    | '/api/v1/topics'
    | '/api/v1/topics/$id/entries/$slug'
    | '/api/v1/topics/$id/entries'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/llms.txt'
    | '/new'
    | '/entries/$slug'
    | '/topics/$id'
    | '/api/'
    | '/topics/'
    | '/api/v1/$'
    | '/api/v1/dump'
    | '/api/v1/graph'
    | '/api/v1/schema'
    | '/api/v1/search'
    | '/api/v1/'
    | '/api/v1/entries/$id'
    | '/api/v1/refs/$key'
    | '/api/v1/topics/$id'
    | '/api/v1/entries/'
    | '/api/v1/refs/'
    | '/api/v1/topics/'
    | '/api/v1/topics/$id/entries/$slug'
    | '/api/v1/topics/$id/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NewRoute: typeof NewRoute
  EntriesSlugRoute: typeof EntriesSlugRoute
  TopicsIdRoute: typeof TopicsIdRoute
  ApiIndexRoute: typeof ApiIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1DumpRoute: typeof ApiV1DumpRoute
  ApiV1GraphRoute: typeof ApiV1GraphRoute
  ApiV1SchemaRoute: typeof ApiV1SchemaRoute
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiV1EntriesIdRoute: typeof ApiV1EntriesIdRoute
  ApiV1RefsKeyRoute: typeof ApiV1RefsKeyRoute
  ApiV1TopicsIdRoute: typeof ApiV1TopicsIdRouteWithChildren
  ApiV1EntriesIndexRoute: typeof ApiV1EntriesIndexRoute
  ApiV1RefsIndexRoute: typeof ApiV1RefsIndexRoute
  ApiV1TopicsIndexRoute: typeof ApiV1TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$slug': {
      id: '/entries/$slug'
      path: '/entries/$slug'
      fullPath: '/entries/$slug'
      preLoaderRoute: typeof EntriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$id': {
      id: '/topics/$id'
      path: '/topics/$id'
      fullPath: '/topics/$id'
      preLoaderRoute: typeof TopicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dump': {
      id: '/api/v1/dump'
      path: '/api/v1/dump'
      fullPath: '/api/v1/dump'
      preLoaderRoute: typeof ApiV1DumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/graph': {
      id: '/api/v1/graph'
      path: '/api/v1/graph'
      fullPath: '/api/v1/graph'
      preLoaderRoute: typeof ApiV1GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/schema': {
      id: '/api/v1/schema'
      path: '/api/v1/schema'
      fullPath: '/api/v1/schema'
      preLoaderRoute: typeof ApiV1SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/api/v1/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entries/': {
      id: '/api/v1/entries/'
      path: '/api/v1/entries'
      fullPath: '/api/v1/entries/'
      preLoaderRoute: typeof ApiV1EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entries/$id': {
      id: '/api/v1/entries/$id'
      path: '/api/v1/entries/$id'
      fullPath: '/api/v1/entries/$id'
      preLoaderRoute: typeof ApiV1EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/refs/': {
      id: '/api/v1/refs/'
      path: '/api/v1/refs'
      fullPath: '/api/v1/refs/'
      preLoaderRoute: typeof ApiV1RefsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/refs/$key': {
      id: '/api/v1/refs/$key'
      path: '/api/v1/refs/$key'
      fullPath: '/api/v1/refs/$key'
      preLoaderRoute: typeof ApiV1RefsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/topics/': {
      id: '/api/v1/topics/'
      path: '/api/v1/topics'
      fullPath: '/api/v1/topics/'
      preLoaderRoute: typeof ApiV1TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/topics/$id': {
      id: '/api/v1/topics/$id'
      path: '/api/v1/topics/$id'
      fullPath: '/api/v1/topics/$id'
      preLoaderRoute: typeof ApiV1TopicsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/topics/$id/entries/': {
      id: '/api/v1/topics/$id/entries/'
      path: '/entries'
      fullPath: '/api/v1/topics/$id/entries/'
      preLoaderRoute: typeof ApiV1TopicsIdEntriesIndexRouteImport
      parentRoute: typeof ApiV1TopicsIdRoute
    }
    '/api/v1/topics/$id/entries/$slug': {
      id: '/api/v1/topics/$id/entries/$slug'
      path: '/entries/$slug'
      fullPath: '/api/v1/topics/$id/entries/$slug'
      preLoaderRoute: typeof ApiV1TopicsIdEntriesSlugRouteImport
      parentRoute: typeof ApiV1TopicsIdRoute
    }
  }
}

interface ApiV1TopicsIdRouteChildren {
  ApiV1TopicsIdEntriesSlugRoute: typeof ApiV1TopicsIdEntriesSlugRoute
  ApiV1TopicsIdEntriesIndexRoute: typeof ApiV1TopicsIdEntriesIndexRoute
}

const ApiV1TopicsIdRouteChildren: ApiV1TopicsIdRouteChildren = {
  ApiV1TopicsIdEntriesSlugRoute: ApiV1TopicsIdEntriesSlugRoute,
  ApiV1TopicsIdEntriesIndexRoute: ApiV1TopicsIdEntriesIndexRoute,
}

const ApiV1TopicsIdRouteWithChildren = ApiV1TopicsIdRoute._addFileChildren(
  ApiV1TopicsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NewRoute: NewRoute,
  EntriesSlugRoute: EntriesSlugRoute,
  TopicsIdRoute: TopicsIdRoute,
  ApiIndexRoute: ApiIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1DumpRoute: ApiV1DumpRoute,
  ApiV1GraphRoute: ApiV1GraphRoute,
  ApiV1SchemaRoute: ApiV1SchemaRoute,
  ApiV1SearchRoute: ApiV1SearchRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiV1EntriesIdRoute: ApiV1EntriesIdRoute,
  ApiV1RefsKeyRoute: ApiV1RefsKeyRoute,
  ApiV1TopicsIdRoute: ApiV1TopicsIdRouteWithChildren,
  ApiV1EntriesIndexRoute: ApiV1EntriesIndexRoute,
  ApiV1RefsIndexRoute: ApiV1RefsIndexRoute,
  ApiV1TopicsIndexRoute: ApiV1TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
